In [51]:
import pandas as pd

In [80]:
df = pd.read_csv("ccc.csv",index_col="Unnamed: 0")

In [81]:
x=df["2"][1]

In [82]:
x in df["2"]

False

In [83]:
df[df["4"]<0]

,1,2,3,4,5,6,7,8,0
"[' ', '1', '2', '1', '2', ' ', '2', '1', ' ']",0.0,0.0,0.0,-0.1,0.0,0.0,0.0,0.0,0.0
"['2', '1', '1', ' ', '2', '1', '2', '1', '2']",0.0,0.0,0.0,-0.1,0.0,0.0,0.0,0.0,0.0
"['1', ' ', '2', '1', '2', '1', '2', '1', '2']",0.0,0.0,0.0,-0.1,0.0,0.0,0.0,0.0,0.0
"['2', '1', ' ', '1', '2', '1', '1', '2', '2']",0.0,0.0,0.0,-0.1,0.0,0.0,0.0,0.0,0.0
"['2', '2', '1', ' ', '2', '1', '1', '1', '2']",0.0,0.0,0.0,-0.1,0.0,0.0,0.0,0.0,0.0
"['1', '2', ' ', '1', '2', '1', ' ', '2', ' ']",0.0,0.0,0.0,-0.1,0.0,0.0,0.0,0.0,0.0

In [84]:
df

,1,2,3,4,5,6,7,8,0
"[' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['1', ' ', ' ', '2', ' ', ' ', ' ', ' ', ' ']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['2', ' ', ' ', '1', ' ', ' ', ' ', ' ', ' ']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['2', '1', ' ', '1', ' ', ' ', ' ', ' ', '2']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['1', '2', ' ', '2', ' ', ' ', ' ', ' ', '1']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['1', '2', '1', '2', ' ', '2', ' ', ' ', '1']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['2', '1', '2', '1', ' ', '1', ' ', ' ', '2']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['2', '1', '2', '1', '1', '1', ' ', '2', '2']",0.0,0.0,0.0,0.1,0.0,0.0,0.0,0.0,0.0
"[' ', ' ', ' ', ' ', '1', ' ', '2', ' ', ' ']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"[' ', ' ', ' ', ' ', '2', ' ', '1', ' ', ' ']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['1', '2', ' ', ' ', '2', ' ', '1', ' ', ' ']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['2', '1', ' ', ' ', '1', ' ', '2', ' ', ' ']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['2', '1', ' ', ' ', '1', '2', '2', '1', ' ']",0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.0,0.0
"[' ', ' ', '2', ' ', ' ', ' ', '1', ' ', ' ']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"[' ', ' ', '1', ' ', ' ', ' ', '2', ' ', ' ']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"[' ', ' ', '1', ' ', ' ', ' ', '2', '1', ' ']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"[' ', ' ', '1', ' ', ' ', ' ', '2', '1', '2']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"[' ', ' ', '2', ' ', ' ', ' ', '1', '2', '1']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['2', ' ', '2', '1', ' ', ' ', '1', '2', '1']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['1', ' ', '1', '2', ' ', ' ', '2', '1', '2']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['1', ' ', '1', '2', '1', '2', '2', '1', '2']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['2', ' ', '2', '1', '2', '1', '1', '2', '1']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['2', '1', '2', '1', '2', '1', '1', '2', '1']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"[' ', ' ', ' ', ' ', '2', ' ', ' ', '1', ' ']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"[' ', ' ', ' ', ' ', '1', ' ', ' ', '2', ' ']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"[' ', '1', ' ', ' ', '1', ' ', ' ', '2', ' ']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['2', '1', ' ', ' ', '1', ' ', ' ', '2', ' ']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['1', '2', ' ', ' ', '2', ' ', ' ', '1', ' ']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['1', '2', ' ', '2', '2', ' ', '1', '1', ' ']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['2', '1', ' ', '1', '1', ' ', '2', '2', ' ']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
"[' ', '2', '2', ' ', ' ', ' ', ' ', '1', '1']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"[' ', '1', '1', ' ', ' ', ' ', ' ', '2', '2']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"[' ', '1', '1', ' ', '2', '1', ' ', '2', '2']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"[' ', '2', '2', ' ', '1', '2', ' ', '1', '1']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['1', '2', '2', ' ', '1', '2', ' ', '1', '1']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['1', '2', '2', '2', '1', '2', ' ', '1', '1']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['1', '2', ' ', '2', ' ', '2', '1', ' ', '1']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['2', '1', ' ', '1', ' ', '1', '2', ' ', '2']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"[' ', '2', ' ', '1', '2', '1', ' ', '2', '1']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['2', '1', '2', '1', ' ', ' ', ' ', ' ', ' ']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['1', '2', '1', '2', ' ', ' ', ' ', ' ', ' ']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['1', '2', '1', '2', ' ', '1', '2', ' ', ' ']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['2', '1', '2', '1', ' ', '2', '1', ' ', ' ']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['2', '1', '2', '1', ' ', '2', '1', ' ', '1']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['2', '1', '2', '1', ' ', '2', '1', '2', '1']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['1', '2', '1', '2', ' ', '1', '2', '1', '2']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['1', '2', '1', '2', '1', '1', '2', '1', '2']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"[' ', ' ', ' ', '2', '1', ' ', '1', '2', ' ']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"[' ', ' ', ' ', '1', '2', ' ', '2', '1', ' ']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"[' ', '2', ' ', '1', '2', '1', '2', '1', ' ']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"[' ', '1', ' ', '2', '1', '2', '1', '2', ' ']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['2', '1', ' ', '2', '1', '2', '1', '2', '1']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['1', '2', ' ', '1', '2', '1', '2', '1', '2']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['2', ' ', '1', ' ', ' ', '1', ' ', ' ', ' ']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['2', ' ', '1', ' ', ' ', '1', ' ', ' ', '2']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['1', ' ', '2', ' ', ' ', '2', ' ', ' ', '1']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['1', ' ', '2', ' ', '2', '2', ' ', '1', '1']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['2', ' ', '1', ' ', '1', '1', ' ', '2', '2']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['2', ' ', '1', '1', '1', '1', ' ', '2', '2']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"['2', '2', '1', '1', '1', '1', ' ', '2', '2']",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0